### ISSUE TITLE
Failed to activate the atomtools package

### ISSUE THREAD

**Issue by poyhsiao** [paradoxxxzero/atomtools#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0-2337254
**System**: Mac OS X 10.10.4
**Thrown From**: [atomtools](https://github.com/paradoxxxzero/atomtools) package, v0.1.0
### Stack Trace

Failed to activate the atomtools package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/kimhsiao/.atom/packages/atomtools/lib/atomtools.coffee:3:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:770:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -1:35.9.0 open-recent:open-recent-path-2 (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:05.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:02.7.0 atomtools:trim-and-newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-compile-coffee",
      "ask-stack",
      "minimap"
    ],
    "audioBeep": false,
    "themes": [
      "atom-soda-dark-ui",
      "monokai-soda"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-soda-dark-ui, v0.9.0
atomtools, v0.1.0
auto-update-packages, v1.0.0
autoclose-html, v0.17.1
autocomplete-paths, v1.0.2
color-picker, v2.0.4
css-color-highlight, v0.3.0
docblockr, v0.7.2
editor-stats, v0.17.0
editorconfig, v1.0.0
file-icons, v1.5.7
hex, v0.6.2
language-cjsx, v0.3.0
language-iced-coffeescript, v0.1.0
language-jade, v0.4.0
linter, v0.12.6
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-js-yaml, v1.0.1
linter-jshint, v0.1.6
linter-jsxhint, v0.1.2
linter-php, v0.0.15
linter-shellcheck, v0.0.8
markdown-format, v2.5.1
minimap-git-diff, v4.1.3
minimap-highlight-selected, vundefined
monokai-soda, v0.5.0
open-recent, v2.2.4
react, v0.12.0
terminal-status, v1.6.7
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by ttaylordev** [comment]
confirmed. windows 7 atom -v (1.6.1)

```
TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (file:///C:/Users/Tyson/.atom/packages/atomtools/lib/atomtools.coffee:3:23)
    at Package.module.exports.Package.activateNow (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:181:20)
    at C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:155:32
    at Package.module.exports.Package.measure (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:148:26
    at Package.module.exports.Package.activate (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\atom-environment.js:688:21)
    at module.exports (C:\Users\Tyson\AppData\Local\atom\app-1.6.1\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Tyson/AppData/Local/atom/app-1.6.1/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Tyson/AppData/Local/atom/app-1.6.1/resources/app.asar/static/index.js:41:9)
```
